#version 450 core

#define TERRAIN_SET 0
#define TERRAIN_BINDING 0
#include "terrain_buffer.include"
#include "circumcircle.include"

#define WORK_GROUP_SIZE 128

layout(local_size_x = WORK_GROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

void main()
{
	const uint thid = gl_GlobalInvocationID.x;

	for (uint ii = thid; ii < num_nodes; ii += WORK_GROUP_SIZE)
	{
		terrain_buffer.data[ii].instance_count = 0;
	}
}